apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-file-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-file-app
  template:
    metadata:
      labels:
        app: node-file-app
    spec:
      containers:
      - name: node-file-app
        image: hitesh008/node-file-demo:01
        volumeMounts:
          - name: myvol
            mountPath: /app  # Mount the directory instead of the file
      volumes:
        - name: myvol
          hostPath:
            path: /mydata  # Mount the directory containing emails.txt
            type: DirectoryOrCreate  # Ensures the directory is created if it doesn't exist

---

apiVersion: v1
kind: Service
metadata:
  name: service-node-file-app
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 3000
  selector:
    app: node-file-app
  type: LoadBalancer
